In [99]:
from sklearn.ensemble import RandomForestRegressor as RFR

In [100]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split as tts

In [101]:
dataset = pd.read_csv("C:\\Users\\Sid\\Desktop\\os\\a.csv")

In [102]:
xtrain  = dataset.drop(['TQ'] ,1)
ytrain = dataset[['TQ']]

In [103]:
xtrain.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2481 entries, 0 to 2480
Data columns (total 5 columns):
Unnamed: 0    2481 non-null int64
Unnamed: 1    2481 non-null int64
Unnamed: 2    2481 non-null int64
Unnamed: 3    2481 non-null int64
Unnamed: 4    2481 non-null int64
dtypes: int64(5)
memory usage: 97.0 KB

In [104]:
ytrain.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2481 entries, 0 to 2480
Data columns (total 1 columns):
TQ    2481 non-null int64
dtypes: int64(1)
memory usage: 19.5 KB

In [105]:
x_train, x_test, y_train, y_test = tts(xtrain, ytrain, test_size = 0.2, random_state = 42)

In [106]:
rf = RFR()

In [107]:
rf.fit(x_train, y_train)

C:\Users\Sid\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\sklearn\ensemble\forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Sid\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [130]:
x_test

      Unnamed: 0  Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4
254           22          37           0          72          84
621          133          76          35         213           0
1730          42           0           0           0          97
1792          56         140           0           0          52
819           76          19           0         157           0
1583          19         139          50           0           0
879           98          41           1         179           0
1414           8          96         107           0           0
2164         144         164           0          95           0
497          150          93           0          18         230
1089           0           0          86         166          29
432          122          65           0           0         202
1929          75         159          19           0          71
1576          26         146          57           0           0
798           97          40           0         178           0
56             1           0          15          45          60
986            0           0          49         129           0
178            0           0           0          19          31
2044          65           0         117         205         121
1266           0           1           0           0           8
1761          11           0           0           0          66
1508           0           0         153           0           9
1273           0          90          51           0          97
2349           0         148           0          79         128
1808          40         124           0           0          36
808           87          30           0         168           0
1983           0           0          22         110          26
1394           0          20          31           0           0
1071           0           0         104         184          47
43             0           0           1          31          46
...          ...         ...         ...         ...         ...
1110           0           0          65         145           8
1018           0           0          17          97           0
84             4           0          19           0           0
1632           0         159          70           0          39
2031          78           0         130         218         134
1655           0         136          47           0          16
1836          12          96           0           0           8
2195         113         133           0          64           0
461           93          36           0           0         173
109           50           6          65           0          20
2082          27           0          79         167          83
354            0          34           0          69         211
1014           0           0          21         101           0
873          104          47           7         185           0
695           18           0           0          99           0
554           38           0           0         118           0
290            0           0           0          35         177
1087           0           0          88         168          31
1304           0          59          20           0          66
416            6           0           0           0          86
472           82          25           0           0         162
923          151          94          53         232          12
2019          90           0         142         230         146
402           20           0           0           0         100
1805          43         127           0           0          39
810           85          28           0         166           0
1813          35         119           0           0          31
2032          77           0         129         217         133
2400           0          97           0          28          77
1488          10           1        1159           2           1

[497 rows x 5 columns]

In [141]:
#y_pred = rf.predict(x_test)
y_pred = rf.predict([[10,1,1159,5,111]])

In [142]:
y_pred.round()

array([103.])

In [110]:
x_train.iloc[0]

Unnamed: 0     0
Unnamed: 1     5
Unnamed: 2    10
Unnamed: 3    40
Unnamed: 4    52
Name: 212, dtype: int64

In [111]:
from xgboost.sklearn import XGBRegressor  
xgbreg = XGBRegressor()

In [112]:
y_test1 = xgbreg.predict(x_train[0:1])

XGBoostError: need to call fit or load_model beforehand

In [113]:
y_test1

NameError: name 'y_test1' is not defined

In [114]:
df = pd.DataFrame([10, 1, 1159, 2, 1])

In [115]:
df_test = pd.DataFrame(np.array(df).transpose())

In [116]:
x_test.iloc[-1] = [10, 1, 1159, 2, 1]

C:\Users\Sid\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\pandas\core\indexing.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
C:\Users\Sid\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [117]:
x_test

      Unnamed: 0  Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4
254           22          37           0          72          84
621          133          76          35         213           0
1730          42           0           0           0          97
1792          56         140           0           0          52
819           76          19           0         157           0
1583          19         139          50           0           0
879           98          41           1         179           0
1414           8          96         107           0           0
2164         144         164           0          95           0
497          150          93           0          18         230
1089           0           0          86         166          29
432          122          65           0           0         202
1929          75         159          19           0          71
1576          26         146          57           0           0
798           97          40           0         178           0
56             1           0          15          45          60
986            0           0          49         129           0
178            0           0           0          19          31
2044          65           0         117         205         121
1266           0           1           0           0           8
1761          11           0           0           0          66
1508           0           0         153           0           9
1273           0          90          51           0          97
2349           0         148           0          79         128
1808          40         124           0           0          36
808           87          30           0         168           0
1983           0           0          22         110          26
1394           0          20          31           0           0
1071           0           0         104         184          47
43             0           0           1          31          46
...          ...         ...         ...         ...         ...
1110           0           0          65         145           8
1018           0           0          17          97           0
84             4           0          19           0           0
1632           0         159          70           0          39
2031          78           0         130         218         134
1655           0         136          47           0          16
1836          12          96           0           0           8
2195         113         133           0          64           0
461           93          36           0           0         173
109           50           6          65           0          20
2082          27           0          79         167          83
354            0          34           0          69         211
1014           0           0          21         101           0
873          104          47           7         185           0
695           18           0           0          99           0
554           38           0           0         118           0
290            0           0           0          35         177
1087           0           0          88         168          31
1304           0          59          20           0          66
416            6           0           0           0          86
472           82          25           0           0         162
923          151          94          53         232          12
2019          90           0         142         230         146
402           20           0           0           0         100
1805          43         127           0           0          39
810           85          28           0         166           0
1813          35         119           0           0          31
2032          77           0         129         217         133
2400           0          97           0          28          77
1488          10           1        1159           2           1

[497 rows x 5 columns]

In [118]:
y_test_1 = rf.predict(np.array(x_test.iloc[-1]).reshape(1,-1))

In [129]:
y_test

       TQ
254    72
621   133
1730   42
1792   56
819    19
1583   19
879     1
1414   96
2164  164
497    18
1089   29
432   122
1929   19
1576   26
798    97
56     45
986    49
178    19
2044  205
1266    1
1761   11
1508    9
1273   90
2349  148
1808   40
808    87
1983   22
1394   20
1071   47
43     31
...   ...
1110    8
1018   17
84      4
1632   39
2031  218
1655   16
1836   12
2195  133
461    93
109     6
2082   79
354    69
1014   21
873     7
695    18
554    38
290    35
1087   31
1304   59
416     6
472    25
923    12
2019  230
402    20
1805   43
810    28
1813   35
2032  217
2400   28
1488   23

[497 rows x 1 columns]

In [120]:
from sklearn.metrics import mean_squared_error as mse

In [121]:
y_pred.round()

array([ 72., 133.,  42.,  55.,  20.,  20.,  11.,  51., 164.,  10.,  29.,
       122.,  19.,  25.,  97.,  45.,  47.,  19., 194.,   2.,  10.,   8.,
        90., 147.,  39.,  87.,  22.,  19.,  46.,  31., 130.,   9.,  23.,
        28.,  32., 113., 124.,  27.,   4., 146.,  17.,  17.,  47.,  18.,
         7.,  12.,   5.,  11., 211.,  40.,  44.,  56., 204.,  89.,  13.,
        19.,   6.,   2.,  46.,  11., 202.,  10.,  12.,  69.,  35.,  12.,
       125.,   8.,   4.,   6.,  42.,  79., 104.,  47.,  23.,  22.,  24.,
        49.,  22.,  11.,   7., 146.,  83., 110.,  48.,  18., 158.,  62.,
        14.,  24., 162.,  13.,  80.,   7.,   2.,  18.,  10.,   8., 223.,
         6.,  16.,  16.,  15., 110., 120.,  19.,  13.,  40.,  62.,  27.,
         2.,  70., 123.,  89.,   9.,  42., 160.,  40.,   5.,  49.,  10.,
        97., 212.,   9.,  84.,   9.,  44.,   7.,  67.,  92.,   1.,   9.,
       165.,  18., 100.,   3., 130.,  21.,   6.,  57.,  42.,  33.,  46.,
         9.,   1.,  13.,  24., 178.,  27.,   4.,  14.,   5.,  32., 133.,
        32., 114.,   1.,  16.,  10.,  27.,   3.,  18.,  78.,   9.,  14.,
       133.,  14.,  30.,  92.,  18.,  11.,   8.,   6.,  60.,  22.,  16.,
       114.,  14., 116., 142.,  15.,  64.,  28.,  93.,  14.,   3.,   1.,
        41.,  12.,  14., 113.,  82., 106.,  23.,   2., 193.,  24.,  30.,
       128.,  43.,  64.,  44.,   8.,  47.,  19., 232.,  40.,   5.,  27.,
        88., 229.,  99., 124.,  52., 234.,  83.,   4., 135.,  53.,  18.,
         6., 137.,  22.,  54.,  15.,   4., 135.,  20., 119.,  26.,  19.,
        11.,  44., 241.,   5.,  12.,  26.,  79.,  24.,  18.,  35., 138.,
       127.,  10.,  31.,  91.,  62.,  38.,  62.,   9.,  16.,   6.,   7.,
       118.,   6.,  74., 137.,  44.,  12., 133., 137.,  33.,  24.,  79.,
        57.,  15.,  71.,  42.,  15.,   3.,   9.,  24.,  34.,  45.,   5.,
       100.,   4.,   9.,   8.,  55.,   6.,  12.,  28.,  13.,  44.,  46.,
       236.,  14.,   7.,   4., 198.,  59.,  15.,  12.,  32.,  44., 223.,
       145., 167., 168.,  24., 136.,  80.,  16.,   3.,  18.,  10.,  68.,
       215.,  23.,  42.,   9.,  25.,  54., 118.,  37.,  88.,   6.,  49.,
        16.,  20.,  14.,   9., 121.,  12., 228.,  19.,  29.,  70.,  36.,
        11., 228., 128.,  42.,  13.,  12.,  28.,  52.,  14.,  10.,  21.,
        36.,   8.,  92., 225., 114.,  40.,   4.,  53., 226., 240.,  98.,
         3.,   9.,  14.,  51.,  29.,  16.,  13.,   7.,  54.,  52.,  21.,
        19., 139., 238.,  54.,  13.,   8., 126., 122.,  22.,  36.,  94.,
       104.,  20.,   5.,   6., 153.,   4.,   2.,  59.,  14., 109., 222.,
        81.,  33.,  37.,   3.,   5.,   8.,  16.,  44.,  12.,  16.,  11.,
        86.,  57.,  16.,   2.,   6.,   2.,  14.,   6.,  72.,   7.,  67.,
         3.,  27.,  13.,  11.,  22., 128.,   1.,  64., 229.,  11., 138.,
         7.,  35., 137.,  20.,  50., 218.,  51.,  23.,  66.,   5.,  14.,
        11.,  38.,  17.,  33., 102.,  33.,  34., 121.,  20.,  10.,  14.,
        31.,  26.,  17.,  10., 135., 106.,  38.,  12.,  17.,  37., 117.,
        33.,  86.,  19.,  26.,  89.,  35.,  15.,   2.,  10., 150.,  32.,
       217., 130.,   5.,  15., 201.,   8.,  16.,   4.,  39., 219.,  15.,
        12., 133.,  92.,   5.,  78.,  68.,  21.,   6.,  19.,  37.,  35.,
        30.,  27.,   6.,  24.,  12., 230.,  20.,  42.,  68.,  35., 217.,
        28.,  22.])

In [125]:
acc = 0
for i in range(len(y_test)):
    if np.array(y_test)[i] == y_pred.round()[i]:
        acc = acc+1
    elif abs(np.array(y_test)[i]-y_pred.round()[i]) in range(1,5):
        acc = acc+1
acc

457

In [126]:
len(y_test)

497

In [127]:
acc/497

0.9195171026156942